import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Avatar } from '@/components/Avatar';
import { Glass } from '@/components/Glass';
import { PressableScale } from '@/components/PressableScale';
import { Screen } from '@/components/Screen';
import { SectionLabel } from '@/components/SectionLabel';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
export default function AdminScreen() { const colors = useColors(); const { pending, approveAccount, rejectAccount } = useApp(); return <Screen><View style={styles.top}><PressableScale onPress={() => router.back()}><Ionicons name="chevron-back" size={28} color={colors.foreground} /></PressableScale><Text style={[styles.title, { color: colors.foreground }]}>Admin area</Text><View style={{ width: 28 }} /></View><Text style={[styles.heading, { color: colors.foreground }]}>Keep the team connected.</Text><Text style={[styles.intro, { color: colors.mutedForeground }]}>Review new registrations and manage workspace access.</Text><SectionLabel> PENDING REGISTRATIONS · {pending.length}</SectionLabel>{pending.length ? pending.map((account) => <Glass key={account.id} style={styles.card}><View style={styles.account}><Avatar label={account.avatar} size={48} tone="amber" /><View style={styles.copy}><Text style={[styles.name, { color: colors.foreground }]}>{account.name}</Text><Text style={[styles.email, { color: colors.mutedForeground }]}>{account.email}</Text><Text style={[styles.request, { color: colors.primary }]}>{account.requestedRole} · {account.date}</Text></View></View><View style={styles.actions}><PressableScale onPress={() => rejectAccount(account.id)} style={[styles.action, { backgroundColor: colors.secondary }]}><Text style={[styles.actionText, { color: colors.secondaryForeground }]}>Reject</Text></PressableScale><PressableScale onPress={() => approveAccount(account.id)} style={[styles.action, { backgroundColor: colors.primary }]}><Text style={styles.approveText}>Approve</Text></PressableScale></View></Glass>) : <Glass style={styles.empty}><Ionicons name="checkmark-circle-outline" size={32} color={colors.success} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>You’re all caught up</Text><Text style={[styles.email, { color: colors.mutedForeground }]}>There are no pending registrations.</Text></Glass>}<SectionLabel>MANAGEMENT TOOLS</SectionLabel><Glass style={styles.tools}><PressableScale onPress={() => Alert.alert('Announcements', 'Announcement composer is ready for the Supabase-backed Version 2.')} style={styles.toolRow}><Ionicons name="megaphone-outline" size={19} color={colors.primary} /><Text style={[styles.toolText, { color: colors.foreground }]}>Manage announcements</Text><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} /></PressableScale><PressableScale onPress={() => Alert.alert('Groups', 'Group creation and member management are scaffolded for Version 2.')} style={styles.toolRow}><Ionicons name="people-outline" size={19} color={colors.primary} /><Text style={[styles.toolText, { color: colors.foreground }]}>Manage groups</Text><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} /></PressableScale></Glass></Screen>; }
const styles = StyleSheet.create({ top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 }, title: { fontFamily: 'Inter_700Bold', fontSize: 17 }, heading: { fontFamily: 'Inter_700Bold', fontSize: 26, letterSpacing: -0.8 }, intro: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21, marginTop: 7, marginBottom: 28 }, card: { padding: 16, borderRadius: 20, marginBottom: 12 }, account: { flexDirection: 'row', gap: 13 }, copy: { flex: 1, gap: 4 }, name: { fontFamily: 'Inter_700Bold', fontSize: 15 }, email: { fontFamily: 'Inter_400Regular', fontSize: 12 }, request: { fontFamily: 'Inter_600SemiBold', fontSize: 11, marginTop: 2 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 16 }, action: { borderRadius: 13, paddingHorizontal: 17, paddingVertical: 10 }, actionText: { fontFamily: 'Inter_600SemiBold', fontSize: 12 }, approveText: { color: '#fff', fontFamily: 'Inter_600SemiBold', fontSize: 12 }, empty: { padding: 26, alignItems: 'center', gap: 8, borderRadius: 20, marginBottom: 28 }, emptyTitle: { fontFamily: 'Inter_700Bold', fontSize: 16 }, tools: { paddingHorizontal: 16, borderRadius: 20 }, toolRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12 }, toolText: { flex: 1, fontFamily: 'Inter_600SemiBold', fontSize: 14 } });