import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Avatar } from '@/components/Avatar';
import { Glass } from '@/components/Glass';
import { PressableScale } from '@/components/PressableScale';
import { Screen } from '@/components/Screen';
import { SectionLabel } from '@/components/SectionLabel';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
export default function AdminScreen() { const colors = useColors(); const { pending, approveAccount, rejectAccount } = useApp(); const tool = (icon: keyof typeof Ionicons.glyphMap, title: string, onPress: () => void) => <PressableScale onPress={onPress} style={[styles.toolRow, { borderBottomColor: colors.border }]}><Ionicons name={icon} size={19} color={colors.primary} /><Text style={[styles.toolText, { color: colors.foreground }]}>{title}</Text><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} /></PressableScale>; return <Screen><View style={styles.top}><PressableScale onPress={() => router.back()}><Ionicons name="chevron-back" size={28} color={colors.foreground} /></PressableScale><Text style={[styles.title, { color: colors.foreground }]}>Admin console</Text><View style={{ width: 28 }} /></View><Text style={[styles.heading, { color: colors.foreground }]}>Manage staff access.</Text><Text style={[styles.intro, { color: colors.mutedForeground }]}>Review account requests and manage your local workplace preview.</Text><SectionLabel> PENDING ACCOUNTS · {pending.length}</SectionLabel>{pending.length ? pending.map((account) => <Glass key={account.id} style={styles.card}><View style={styles.account}><Avatar label={account.avatar} size={48} tone="amber" /><View style={styles.copy}><Text style={[styles.name, { color: colors.foreground }]}>{account.name}</Text><Text style={[styles.email, { color: colors.mutedForeground }]}>{account.email}</Text><Text style={[styles.request, { color: colors.primary }]}>{account.requestedRole} · {account.date}</Text></View></View><View style={styles.actions}><PressableScale onPress={() => rejectAccount(account.id)} style={[styles.action, { backgroundColor: colors.secondary }]}><Text style={[styles.actionText, { color: colors.secondaryForeground }]}>Reject</Text></PressableScale><PressableScale onPress={() => approveAccount(account.id)} style={[styles.action, { backgroundColor: colors.royalBlue }]}><Text style={styles.approveText}>Approve</Text></PressableScale></View></Glass>) : <Glass style={styles.empty}><Ionicons name="checkmark-circle-outline" size={32} color={colors.success} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>You’re all caught up</Text><Text style={[styles.email, { color: colors.mutedForeground }]}>There are no pending registrations.</Text></Glass>}<SectionLabel>MANAGEMENT TOOLS</SectionLabel><Glass style={styles.tools}>{tool('people-outline', 'Staff directory', () => router.push('/(tabs)/directory'))}{tool('megaphone-outline', 'Announcements', () => router.push('/(tabs)/announcements'))}{tool('chatbubbles-outline', 'Groups', () => router.push('/new-chat'))}{tool('call-outline', 'Emergency contacts', () => router.push('/emergency-contacts'))}{tool('document-text-outline', 'Audit log', () => Alert.alert('Audit log', 'Local preview: approvals and rejects are available during this session.'))}</Glass></Screen>; }
const styles = StyleSheet.create({ top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 }, title: { fontFamily: 'Inter_500Medium', fontSize: 18 }, heading: { fontFamily: 'Inter_500Medium', fontSize: 25, letterSpacing: -0.6 }, intro: { fontFamily: 'Inter_400Regular', fontSize: 16, lineHeight: 23, marginTop: 7, marginBottom: 22 }, card: { padding: 16, borderRadius: 12, marginBottom: 12 }, account: { flexDirection: 'row', gap: 13 }, copy: { flex: 1, gap: 4 }, name: { fontFamily: 'Inter_500Medium', fontSize: 16 }, email: { fontFamily: 'Inter_400Regular', fontSize: 13 }, request: { fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: 2 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 16 }, action: { borderRadius: 18, paddingHorizontal: 17, paddingVertical: 10 }, actionText: { fontFamily: 'Inter_500Medium', fontSize: 13 }, approveText: { color: '#fff', fontFamily: 'Inter_500Medium', fontSize: 13 }, empty: { padding: 26, alignItems: 'center', gap: 8, borderRadius: 12, marginBottom: 22 }, emptyTitle: { fontFamily: 'Inter_500Medium', fontSize: 16 }, tools: { paddingHorizontal: 16, borderRadius: 12 }, toolRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1 }, toolText: { flex: 1, fontFamily: 'Inter_500Medium', fontSize: 16 } });