import { router } from 'expo-router';
import React from 'react';
import { Image, KeyboardAvoidingView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { PressableScale } from '@/components/PressableScale';
import { useColors } from '@/hooks/useColors';

export default function WelcomeScreen() {
  const colors = useColors();
  const [email, setEmail] = React.useState('');
  const [password, setPassword] = React.useState('');
  return <KeyboardAvoidingView behavior="padding" style={[styles.root, { backgroundColor: colors.background }]}>
    <View style={styles.brand}><Image source={require('@/assets/images/company-logo.png')} style={styles.logo} accessibilityLabel="Bridging Abilities company logo" /><Text style={[styles.brandName, { color: colors.foreground }]}>Bridging Abilities Staff</Text><Text style={[styles.tagline, { color: colors.mutedForeground }]}>Private team communication</Text></View>
    <View style={styles.bottom}><Text style={[styles.welcome, { color: colors.foreground }]}>Sign in</Text><Text style={[styles.copy, { color: colors.mutedForeground }]}>Use your work account to continue.</Text><Text style={[styles.label, { color: colors.mutedForeground }]}>WORK EMAIL</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@bridgingabilities.com.au" placeholderTextColor={colors.mutedForeground} style={[styles.input, { backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} /><Text style={[styles.label, { color: colors.mutedForeground }]}>PASSWORD</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" placeholderTextColor={colors.mutedForeground} style={[styles.input, { backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} /><Text style={[styles.helper, { color: colors.mutedForeground }]}>Forgotten your password? Contact your manager to have it reset.</Text><PressableScale onPress={() => router.replace('/policy')} style={[styles.primary, { backgroundColor: colors.royalBlue }]}><Text style={styles.primaryText}>Sign in</Text><Ionicons name="arrow-forward" size={18} color="#fff" /></PressableScale><Text style={[styles.note, { color: colors.mutedForeground }]}>Access is limited to Bridging Abilities staff.</Text></View>
  </KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1, paddingHorizontal: 26, justifyContent: 'space-between', paddingTop: 60, paddingBottom: 34 }, brand: { alignItems: 'center' }, logo: { width: 150, height: 150, resizeMode: 'contain', marginBottom: 8 }, brandName: { fontFamily: 'Inter_500Medium', fontSize: 22, letterSpacing: -0.4 }, tagline: { fontFamily: 'Inter_400Regular', fontSize: 14, marginTop: 8 }, bottom: { gap: 10 }, welcome: { fontFamily: 'Inter_500Medium', fontSize: 24, letterSpacing: -0.5 }, copy: { fontFamily: 'Inter_400Regular', fontSize: 16, marginBottom: 5 }, label: { fontFamily: 'Inter_500Medium', fontSize: 12, letterSpacing: 0.8, marginTop: 7 }, input: { height: 52, borderRadius: 12, borderWidth: 1, paddingHorizontal: 14, fontFamily: 'Inter_400Regular', fontSize: 16 }, helper: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 20, marginTop: 2, marginBottom: 6 }, primary: { minHeight: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10, marginTop: 4 }, primaryText: { color: '#fff', fontFamily: 'Inter_500Medium', fontSize: 16 }, note: { textAlign: 'center', fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 6 } });