import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Glass } from '@/components/Glass';
import { PressableScale } from '@/components/PressableScale';
import { useColors } from '@/hooks/useColors';

export default function PolicyScreen() {
  const colors = useColors(); const [accepted, setAccepted] = useState(false);
  return <View style={[styles.root, { backgroundColor: colors.background }]}><View style={[styles.signature, { backgroundColor: colors.signatureEnd }]} /><ScrollView contentContainerStyle={styles.content}><Ionicons name="shield-checkmark-outline" size={38} color={colors.primary} /><Text style={[styles.title, { color: colors.foreground }]}>Workplace communication policy</Text><Text style={[styles.intro, { color: colors.mutedForeground }]}>Before you enter, please acknowledge how to use Bridging Abilities Staff safely and respectfully.</Text><Glass style={styles.card}><Text style={[styles.cardTitle, { color: colors.foreground }]}>What this means</Text><Text style={[styles.cardCopy, { color: colors.mutedForeground }]}>Keep messages relevant to work, protect personal information, and use emergency services when immediate help is needed. This app is not a replacement for incident reporting procedures.</Text></Glass><View style={[styles.acknowledgement, { borderColor: colors.border }]}><Switch value={accepted} onValueChange={setAccepted} trackColor={{ false: colors.input, true: colors.primary }} /><Text style={[styles.ackCopy, { color: colors.foreground }]}>I have read and agree to the workplace communication policy.</Text></View><PressableScale disabled={!accepted} onPress={() => router.replace('/(tabs)')} style={[styles.continue, { backgroundColor: accepted ? colors.royalBlue : colors.input }]}><Text style={[styles.continueText, { color: accepted ? '#fff' : colors.mutedForeground }]}>Accept and continue</Text></PressableScale></ScrollView></View>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, signature: { height: 3 }, content: { paddingHorizontal: 24, paddingTop: 64, paddingBottom: 36, alignItems: 'center' }, title: { fontFamily: 'Inter_500Medium', fontSize: 24, textAlign: 'center', marginTop: 18 }, intro: { fontFamily: 'Inter_400Regular', fontSize: 16, lineHeight: 23, textAlign: 'center', marginTop: 10, marginBottom: 24 }, card: { padding: 18, borderRadius: 12 }, cardTitle: { fontFamily: 'Inter_500Medium', fontSize: 17, marginBottom: 8 }, cardCopy: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 22 }, acknowledgement: { flexDirection: 'row', gap: 12, alignItems: 'center', borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 18, marginTop: 22 }, ackCopy: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 21 }, continue: { minHeight: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center', alignSelf: 'stretch', marginTop: 28 }, continueText: { fontFamily: 'Inter_500Medium', fontSize: 16 } });