import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { KeyboardAvoidingView, StyleSheet, Text, TextInput, View } from 'react-native';
import { PressableScale } from '@/components/PressableScale';
import { useColors } from '@/hooks/useColors';

export default function SetPasswordScreen() {
  const colors = useColors(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const valid = password.length >= 8 && password === confirm;
  return <KeyboardAvoidingView behavior="padding" style={[styles.root, { backgroundColor: colors.background }]}><View style={[styles.signature, { backgroundColor: colors.signatureEnd }]} /><View style={styles.content}><PressableScale onPress={() => router.back()}><Ionicons name="chevron-back" size={27} color={colors.foreground} /></PressableScale><Ionicons name="lock-closed-outline" size={38} color={colors.primary} style={styles.icon} /><Text style={[styles.title, { color: colors.foreground }]}>Set your password</Text><Text style={[styles.intro, { color: colors.mutedForeground }]}>Create a password with at least eight characters for your staff account.</Text><Text style={[styles.label, { color: colors.mutedForeground }]}>NEW PASSWORD</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="At least 8 characters" placeholderTextColor={colors.mutedForeground} style={[styles.input, { borderColor: colors.border, color: colors.foreground, backgroundColor: colors.card }]} /><Text style={[styles.label, { color: colors.mutedForeground }]}>CONFIRM PASSWORD</Text><TextInput value={confirm} onChangeText={setConfirm} secureTextEntry placeholder="Repeat your password" placeholderTextColor={colors.mutedForeground} style={[styles.input, { borderColor: colors.border, color: colors.foreground, backgroundColor: colors.card }]} /><PressableScale disabled={!valid} onPress={() => router.replace('/policy')} style={[styles.button, { backgroundColor: valid ? colors.royalBlue : colors.input }]}><Text style={[styles.buttonText, { color: valid ? '#fff' : colors.mutedForeground }]}>Continue</Text></PressableScale></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, signature: { height: 3 }, content: { flex: 1, paddingHorizontal: 24, paddingTop: 28 }, icon: { alignSelf: 'center', marginTop: 64 }, title: { fontFamily: 'Inter_500Medium', fontSize: 24, textAlign: 'center', marginTop: 18 }, intro: { fontFamily: 'Inter_400Regular', fontSize: 16, lineHeight: 23, textAlign: 'center', marginTop: 9, marginBottom: 30 }, label: { fontFamily: 'Inter_500Medium', fontSize: 12, letterSpacing: .7, marginBottom: 7, marginTop: 12 }, input: { height: 52, borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, fontFamily: 'Inter_400Regular', fontSize: 16 }, button: { height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: 26, marginTop: 28 }, buttonText: { fontFamily: 'Inter_500Medium', fontSize: 16 } });