import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, StyleSheet, Switch, Text, View } from 'react-native';
import { Glass } from '@/components/Glass';
import { PressableScale } from '@/components/PressableScale';
import { Screen } from '@/components/Screen';
import { SectionLabel } from '@/components/SectionLabel';
import { TopBar } from '@/components/TopBar';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';

export default function SettingsScreen() {
  const colors = useColors(); const { user, isDark, toggleTheme, pending } = useApp();
  const row = (icon: keyof typeof Ionicons.glyphMap, title: string, subtitle: string, onPress?: () => void, trailing?: React.ReactNode) => <PressableScale onPress={onPress} style={styles.press}><View style={[styles.row, { borderBottomColor: colors.border }]}><View style={[styles.icon, { backgroundColor: colors.secondary }]}><Ionicons name={icon} size={18} color={colors.primary} /></View><View style={styles.copy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.rowSub, { color: colors.mutedForeground }]}>{subtitle}</Text></View>{trailing ?? <Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} />}</View></PressableScale>;
  return <Screen><TopBar title="Settings" subtitle="Your workspace preferences" onProfile={() => router.push('/profile')} /><PressableScale onPress={() => router.push('/profile')}><Glass style={styles.profileCard}><View style={[styles.profileAvatar, { backgroundColor: colors.navy }]}><Text style={styles.profileInitials}>{user.avatar}</Text></View><View style={styles.copy}><Text style={[styles.profileName, { color: colors.foreground }]}>{user.name}</Text><Text style={[styles.rowSub, { color: colors.mutedForeground }]}>{user.title}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.mutedForeground} /></Glass></PressableScale><SectionLabel>WORKSPACE</SectionLabel><Glass style={styles.panel}>{row('notifications-outline', 'Notifications', 'Messages, announcements and mentions', () => Alert.alert('Notifications', 'Notification preferences will be connected to Expo push notifications in Version 3.'))}{row('color-palette-outline', 'Appearance', isDark ? 'Dark mode' : 'Light mode', undefined, <Switch value={isDark} onValueChange={toggleTheme} trackColor={{ false: colors.input, true: colors.primary }} thumbColor={colors.glassStrong} />)}{user.role === 'admin' ? row('shield-checkmark-outline', 'Admin area', `${pending.length} pending registrations`, () => router.push('/admin')) : null}</Glass><SectionLabel>ACCOUNT</SectionLabel><Glass style={styles.panel}>{row('help-circle-outline', 'Help & support', 'Get help with Northstar', () => Alert.alert('Help & support', 'Ask your workspace admin for assistance.'))}{row('log-out-outline', 'Sign out', 'You are signed in on this device', () => Alert.alert('Sign out', 'Demo mode keeps your local session active.'))}</Glass><Text style={[styles.version, { color: colors.mutedForeground }]}>Northstar · Version 1.0</Text></Screen>;
}
const styles = StyleSheet.create({ profileCard: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 28 }, profileAvatar: { width: 52, height: 52, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, profileInitials: { color: '#fff', fontFamily: 'Inter_700Bold', fontSize: 16 }, copy: { flex: 1, gap: 4 }, profileName: { fontFamily: 'Inter_700Bold', fontSize: 16 }, panel: { paddingHorizontal: 16, marginBottom: 26, borderRadius: 20 }, press: { width: '100%' }, row: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 13, borderBottomWidth: 1 }, icon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, rowTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14 }, rowSub: { fontFamily: 'Inter_400Regular', fontSize: 12 }, version: { textAlign: 'center', fontFamily: 'Inter_500Medium', fontSize: 11, marginTop: 4 } });