import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, StyleSheet, Switch, Text, View } from 'react-native';
import { Glass } from '@/components/Glass';
import { PressableScale } from '@/components/PressableScale';
import { Screen } from '@/components/Screen';
import { SectionLabel } from '@/components/SectionLabel';
import { TopBar } from '@/components/TopBar';
import { useApp } from '@/context/AppContext';
import { useAuth } from '@/context/AuthContext';
import { useColors } from '@/hooks/useColors';

export default function SettingsScreen() {
  const colors = useColors();
  const { isDark, toggleTheme } = useApp();
  const { profile, signOut } = useAuth();
  const initials = profile?.display_name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase() ?? 'BA';
  const row = (icon: keyof typeof Ionicons.glyphMap, title: string, subtitle: string, onPress?: () => void, trailing?: React.ReactNode) => <PressableScale onPress={onPress} style={styles.press}><View style={[styles.row, { borderBottomColor: colors.border }]}><View style={[styles.icon, { backgroundColor: colors.secondary }]}><Ionicons name={icon} size={18} color={colors.primary} /></View><View style={styles.copy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.rowSub, { color: colors.mutedForeground }]}>{subtitle}</Text></View>{trailing ?? <Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} />}</View></PressableScale>;
  const handleSignOut = () => { signOut(); router.replace('/'); };

  return <Screen><TopBar title="Settings" subtitle="Your account and app preferences" onProfile={() => router.push('/profile')} /><PressableScale onPress={() => router.push('/profile')}><Glass style={styles.profileCard}><View style={[styles.profileAvatar, { backgroundColor: colors.navy }]}><Text style={styles.profileInitials}>{initials}</Text></View><View style={styles.copy}><Text style={[styles.profileName, { color: colors.foreground }]}>{profile?.display_name ?? 'Staff member'}</Text><Text style={[styles.rowSub, { color: colors.mutedForeground }]}>{profile?.role === 'admin' ? 'Administrator' : profile?.role === 'manager' ? 'Manager' : 'Staff member'}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.mutedForeground} /></Glass></PressableScale><SectionLabel>YOUR APP</SectionLabel><Glass style={styles.panel}>{row('notifications-outline', 'Notifications', 'Messages, announcements and mentions', () => Alert.alert('Notifications', 'Push notification preferences will be available when device notifications are enabled.'))}{row('at-outline', 'Mentions & starred', 'Messages saved for you', () => router.push('/mentions'))}{row('call-outline', 'Emergency contacts', 'On-call and workplace support', () => router.push('/emergency-contacts'))}{row('color-palette-outline', 'Appearance', isDark ? 'Dark mode' : 'Light mode', undefined, <Switch value={isDark} onValueChange={toggleTheme} trackColor={{ false: colors.input, true: colors.primary }} thumbColor={colors.glassStrong} />)}</Glass>{profile?.role === 'admin' ? <><SectionLabel>ADMINISTRATION</SectionLabel><Glass style={styles.panel}>{row('person-add-outline', 'Staff access', 'Add staff and reset temporary passwords', () => router.push('/staff-access'))}</Glass></> : null}<SectionLabel>ACCOUNT</SectionLabel><Glass style={styles.panel}>{row('document-text-outline', 'Privacy & policies', 'Workplace communication policy', () => Alert.alert('Privacy & policies', 'Your policy acknowledgement is required before workplace messages are available.'))}{row('help-circle-outline', 'Help & support', 'Contact your manager for help', () => Alert.alert('Help & support', 'Ask your manager or workplace administrator for assistance.'))}{row('log-out-outline', 'Sign out', 'Sign out of this device', handleSignOut)}</Glass><Text style={[styles.version, { color: colors.mutedForeground }]}>Bridging Abilities Staff · Secure access</Text></Screen>;
}

const styles = StyleSheet.create({ profileCard: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 20, borderRadius: 20 }, profileAvatar: { width: 52, height: 52, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, profileInitials: { color: '#fff', fontFamily: 'Inter_500Medium', fontSize: 16 }, copy: { flex: 1, gap: 4 }, profileName: { fontFamily: 'Inter_500Medium', fontSize: 17 }, panel: { paddingHorizontal: 16, marginBottom: 18, borderRadius: 20 }, press: { width: '100%' }, row: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 13, borderBottomWidth: 1 }, icon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, rowTitle: { fontFamily: 'Inter_500Medium', fontSize: 16 }, rowSub: { fontFamily: 'Inter_400Regular', fontSize: 13 }, version: { textAlign: 'center', fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 4 } });