import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, StyleSheet, Switch, Text, View } from 'react-native';
import { Glass } from '@/components/Glass';
import { PressableScale } from '@/components/PressableScale';
import { Screen } from '@/components/Screen';
import { SectionLabel } from '@/components/SectionLabel';
import { TopBar } from '@/components/TopBar';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';

export default function SettingsScreen() {
  const colors = useColors(); const { user, isDark, toggleTheme, pending } = useApp();
  const row = (icon: keyof typeof Ionicons.glyphMap, title: string, subtitle: string, onPress?: () => void, trailing?: React.ReactNode) => <PressableScale onPress={onPress} style={styles.press}><View style={[styles.row, { borderBottomColor: colors.border }]}><View style={[styles.icon, { backgroundColor: colors.secondary }]}><Ionicons name={icon} size={18} color={colors.primary} /></View><View style={styles.copy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.rowSub, { color: colors.mutedForeground }]}>{subtitle}</Text></View>{trailing ?? <Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} />}</View></PressableScale>;
  return <Screen><TopBar title="Settings" subtitle="Your account and app preferences" onProfile={() => router.push('/profile')} /><PressableScale onPress={() => router.push('/profile')}><Glass style={styles.profileCard}><View style={[styles.profileAvatar, { backgroundColor: colors.navy }]}><Text style={styles.profileInitials}>{user.avatar}</Text></View><View style={styles.copy}><Text style={[styles.profileName, { color: colors.foreground }]}>{user.name}</Text><Text style={[styles.rowSub, { color: colors.mutedForeground }]}>{user.title}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.mutedForeground} /></Glass></PressableScale><SectionLabel>YOUR APP</SectionLabel><Glass style={styles.panel}>{row('notifications-outline', 'Notifications', 'Messages, announcements and mentions', () => Alert.alert('Notifications', 'Push notification preferences will be available when device notifications are enabled.'))}{row('at-outline', 'Mentions & starred', 'Messages saved for you', () => router.push('/mentions'))}{row('call-outline', 'Emergency contacts', 'On-call and workplace support', () => router.push('/emergency-contacts'))}{row('color-palette-outline', 'Appearance', isDark ? 'Dark mode' : 'Light mode', undefined, <Switch value={isDark} onValueChange={toggleTheme} trackColor={{ false: colors.input, true: colors.primary }} thumbColor={colors.glassStrong} />)}</Glass>{user.role === 'admin' ? <><SectionLabel>ADMINISTRATION</SectionLabel><Glass style={styles.panel}>{row('shield-checkmark-outline', 'Admin console', `${pending.length} pending account request${pending.length === 1 ? '' : 's'}`, () => router.push('/admin'))}</Glass></> : null}<SectionLabel>ACCOUNT</SectionLabel><Glass style={styles.panel}>{row('document-text-outline', 'Privacy & policies', 'Workplace communication policy', () => Alert.alert('Privacy & policies', 'Policy acknowledgement is stored on-device in this local prototype.'))}{row('help-circle-outline', 'Help & support', 'Contact your manager for help', () => Alert.alert('Help & support', 'Ask your manager or workplace administrator for assistance.'))}{row('log-out-outline', 'Sign out', 'You are signed in on this device', () => router.replace('/'))}</Glass><Text style={[styles.version, { color: colors.mutedForeground }]}>Bridging Abilities Staff · Local preview</Text></Screen>;
}
const styles = StyleSheet.create({ profileCard: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 20, borderRadius: 12 }, profileAvatar: { width: 52, height: 52, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, profileInitials: { color: '#fff', fontFamily: 'Inter_500Medium', fontSize: 16 }, copy: { flex: 1, gap: 4 }, profileName: { fontFamily: 'Inter_500Medium', fontSize: 17 }, panel: { paddingHorizontal: 16, marginBottom: 18, borderRadius: 12 }, press: { width: '100%' }, row: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 13, borderBottomWidth: 1 }, icon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, rowTitle: { fontFamily: 'Inter_500Medium', fontSize: 16 }, rowSub: { fontFamily: 'Inter_400Regular', fontSize: 13 }, version: { textAlign: 'center', fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 4 } });