import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import React, { useState } from 'react';
import { FlatList, KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from 'react-native';
import { Avatar } from '@/components/Avatar';
import { Glass } from '@/components/Glass';
import { PressableScale } from '@/components/PressableScale';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { getSenderColor } from '@/constants/senderColors';
import { staff } from '@/data/mockData';
import { useColorScheme } from 'react-native';

export default function ConversationScreen() {
  const colors = useColors(); const isDark = useColorScheme() === 'dark'; const { id } = useLocalSearchParams<{ id: string }>(); const { conversations, messages, sendMessage } = useApp(); const [text, setText] = useState('');
  const conversation = conversations.find((item) => item.id === id) ?? conversations[0]; const items = messages[conversation.id] ?? [];
  const submit = () => { const trimmed = text.trim(); if (!trimmed) return; sendMessage(conversation.id, trimmed); setText(''); };
  return <KeyboardAvoidingView style={[styles.root, { backgroundColor: colors.background }]} behavior="padding" keyboardVerticalOffset={0}><View style={[styles.header, { borderBottomColor: colors.border }]}><View style={styles.signature} /><View style={styles.headerRow}><PressableScale onPress={() => router.back()} accessibilityLabel="Go back"><Ionicons name="chevron-back" size={28} color={colors.foreground} /></PressableScale><Avatar label={conversation.avatar} size={40} tone={conversation.kind === 'announcement' ? 'amber' : 'teal'} /><View style={styles.headerCopy}><Text style={[styles.headerTitle, { color: colors.foreground }]}>{conversation.name}</Text><Text style={[styles.headerSub, { color: colors.mutedForeground }]}>{conversation.kind === 'announcement' ? 'Broadcast channel' : conversation.subtitle}</Text></View><PressableScale accessibilityLabel="More options" onPress={() => {}}><Ionicons name="ellipsis-horizontal" size={23} color={colors.foreground} /></PressableScale></View></View><FlatList inverted data={[...items].reverse()} keyExtractor={(item) => item.id} contentContainerStyle={styles.messages} keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled" renderItem={({ item }) => { const sender = staff.find((person) => person.id === item.senderId); const senderName = item.outgoing ? 'You' : sender?.name ?? 'Team member'; return <View style={[styles.messageRow, item.outgoing && styles.outgoing]}><Text style={[styles.senderName, { color: item.outgoing ? colors.mutedForeground : getSenderColor(item.senderId, isDark) }]}>{senderName}</Text><View style={[styles.bubble, { backgroundColor: item.outgoing ? colors.royalBlue : colors.bubbleIncoming }]}><Text style={[styles.messageText, { color: item.outgoing ? '#FFFFFF' : colors.messageText }]}>{item.text}</Text><View style={styles.messageMeta}><Text style={[styles.messageTime, { color: item.outgoing ? 'rgba(255,255,255,0.78)' : colors.mutedForeground }]}>{item.time}</Text>{item.outgoing ? <Ionicons name={item.status === 'read' ? 'checkmark-done' : 'checkmark'} size={14} color={item.status === 'read' ? colors.statusDone : 'rgba(255,255,255,0.78)'} /> : null}</View></View></View>; }} /><Glass style={styles.composer} intensity={48}><PressableScale accessibilityLabel="Add attachment" onPress={() => {}}><Ionicons name="add-circle-outline" size={25} color={colors.primary} /></PressableScale><TextInput value={text} onChangeText={setText} onSubmitEditing={submit} returnKeyType="send" placeholder={conversation.kind === 'announcement' ? 'Reply to announcement' : 'Write a message'} placeholderTextColor={colors.mutedForeground} style={[styles.textInput, { color: colors.foreground }]} /><PressableScale accessibilityLabel="Send message" onPress={submit} style={[styles.send, { backgroundColor: text.trim() ? colors.royalBlue : colors.input }]}><Ionicons name="arrow-up" size={19} color={text.trim() ? '#FFFFFF' : colors.mutedForeground} /></PressableScale></Glass></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, header: { paddingTop: 46, paddingBottom: 12, paddingHorizontal: 16, borderBottomWidth: 1 }, headerRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, signature: { height: 3, marginBottom: 10, marginHorizontal: -16, backgroundColor: '#7A2BE0' }, headerCopy: { flex: 1 }, headerTitle: { fontFamily: 'Inter_500Medium', fontSize: 17 }, headerSub: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 2 }, messages: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 14 }, messageRow: { alignItems: 'flex-start', marginBottom: 12 }, outgoing: { alignItems: 'flex-end' }, senderName: { fontFamily: 'Inter_500Medium', fontSize: 13, marginBottom: 4, paddingHorizontal: 4 }, bubble: { maxWidth: '82%', paddingHorizontal: 14, paddingTop: 11, paddingBottom: 8, borderRadius: 18, borderBottomLeftRadius: 4 }, messageText: { fontFamily: 'Inter_400Regular', fontSize: 17, lineHeight: 25 }, messageMeta: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 3, marginTop: 4 }, messageTime: { fontFamily: 'Inter_400Regular', fontSize: 12 }, composer: { marginHorizontal: 14, marginBottom: Platform.OS === 'web' ? 34 : 14, minHeight: 54, borderRadius: 12, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, gap: 9 }, textInput: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 16, maxHeight: 80 }, send: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' } });