import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Avatar } from '@/components/Avatar';
import { Glass } from '@/components/Glass';
import { PressableScale } from '@/components/PressableScale';
import { Screen } from '@/components/Screen';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
export default function PersonScreen() { const colors = useColors(); const { id } = useLocalSearchParams<{ id: string }>(); const { staff } = useApp(); const person = staff.find((item) => item.id === id) ?? staff[0]; return <Screen><View style={styles.top}><PressableScale onPress={() => router.back()}><Ionicons name="chevron-back" size={28} color={colors.foreground} /></PressableScale><Text style={[styles.topTitle, { color: colors.foreground }]}>Staff profile</Text><View style={{ width: 28 }} /></View><View style={styles.hero}><Avatar label={person.avatar} size={92} tone="teal" /><Text style={[styles.name, { color: colors.foreground }]}>{person.name}</Text><Text style={[styles.role, { color: colors.mutedForeground }]}>{person.title} · {person.department}</Text><Text style={[styles.active, { color: colors.success }]}>{person.lastActive}</Text><PressableScale onPress={() => router.push('/conversation/alex-chat')} style={[styles.messageButton, { backgroundColor: colors.primary }]}><Ionicons name="chatbubble-outline" size={17} color="#fff" /><Text style={styles.messageButtonText}>Message</Text></PressableScale></View><Glass style={styles.card}><Text style={[styles.about, { color: colors.foreground }]}>{person.about}</Text></Glass></Screen>; }
const styles = StyleSheet.create({ top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 30 }, topTitle: { fontFamily: 'Inter_700Bold', fontSize: 17 }, hero: { alignItems: 'center', marginBottom: 32 }, name: { fontFamily: 'Inter_700Bold', fontSize: 24, marginTop: 15 }, role: { fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 5 }, active: { fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: 12 }, messageButton: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', borderRadius: 16, paddingHorizontal: 22, paddingVertical: 12, marginTop: 18 }, messageButtonText: { color: '#fff', fontFamily: 'Inter_600SemiBold', fontSize: 14 }, card: { padding: 18, borderRadius: 20 }, about: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 23 } });